# Generated by Django 5.0.2 on 2024-03-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_confirm_password_register_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='confirmPassword',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='user_name',
        ),
    ]
