# Generated by Django 5.0.2 on 2024-04-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipes_user'),
        ('recipes', '0010_recipes_likes'),
    ]

    operations = [
    ]
